# fly.toml app configuration file generated for hackerhouse-frontend on 2023-09-29T17:31:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hackerhouse-frontend"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
